name: citofony_dashboard
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl:
  localization:
  bloc:
  flutter_bloc:
  bloc_test:
  injectable:
  get_it:
  cupertino_icons:
  freezed: ^2.4.1
  freezed_annotation: ^2.4.1
  pretty_string:
  logger:
  logging:
  dio:
  clean_network_annotations:
    git:
      url: https://github.com/phalcondroid/clean_network_annotations.git
  flutter_native_splash:
  flutter_dotenv:
  formz:
  fpdart:
  json_annotation: ^4.9.0
  rflutter_alert: ^2.0.7
  stylish_bottom_bar: ^1.1.1
  shared_preferences: ^2.5.3
  flutter_local_notifications: ^19.1.0
  firebase_messaging: ^15.2.5
  firebase_core: ^3.13.0
  firebase_analytics: ^11.4.5
  table_calendar: ^3.0.9
  permission_handler: ^11.0.0
  flutter_webrtc:
  socket_io_client:
  lucide_icons: ^0.257.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  injectable_generator:
  build_runner:

  clean_network:
    git:
      url: https://github.com/phalcondroid/clean_network.git
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/antenna.png
    - assets/images/logo.png
    - assets/images/market/
    - assets/i18n/en.json
    - assets/i18n/es.json
    - .env
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/nunitoregular.ttf
