// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz9gHbNY7jTMUVeZd1pSDPEe1SnzoSsgM',
    appId: '1:1099428870497:web:4bbe27f5f98c1f5bbead20',
    messagingSenderId: '1099428870497',
    projectId: 'citofony-dashboard-fea5c',
    authDomain: 'citofony-dashboard-fea5c.firebaseapp.com',
    storageBucket: 'citofony-dashboard-fea5c.firebasestorage.app',
    measurementId: 'G-DCYR8HYKZW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoNah0rweeGtIdGuLJx-Z-EU0nqEgSurc',
    appId: '1:1099428870497:android:501cfa0069ef04dcbead20',
    messagingSenderId: '1099428870497',
    projectId: 'citofony-dashboard-fea5c',
    storageBucket: 'citofony-dashboard-fea5c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq3mwzf4FkXHgjSwwEGp0_SmtL-0r-qgQ',
    appId: '1:1099428870497:ios:65094bdd154840a8bead20',
    messagingSenderId: '1099428870497',
    projectId: 'citofony-dashboard-fea5c',
    storageBucket: 'citofony-dashboard-fea5c.firebasestorage.app',
    iosBundleId: 'com.example.citofonyDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDq3mwzf4FkXHgjSwwEGp0_SmtL-0r-qgQ',
    appId: '1:1099428870497:ios:65094bdd154840a8bead20',
    messagingSenderId: '1099428870497',
    projectId: 'citofony-dashboard-fea5c',
    storageBucket: 'citofony-dashboard-fea5c.firebasestorage.app',
    iosBundleId: 'com.example.citofonyDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCz9gHbNY7jTMUVeZd1pSDPEe1SnzoSsgM',
    appId: '1:1099428870497:web:5f810113fa357a78bead20',
    messagingSenderId: '1099428870497',
    projectId: 'citofony-dashboard-fea5c',
    authDomain: 'citofony-dashboard-fea5c.firebaseapp.com',
    storageBucket: 'citofony-dashboard-fea5c.firebasestorage.app',
    measurementId: 'G-CXSQ119KTV',
  );
}
